services:
  app:
    build: .
    ports:
      - "3333:80"
    volumes:
      - ./db:/rails/db
      - ./storage:/rails/storage
      - ./log:/rails/log
    environment:
      - RAILS_ENV=development
      - RAILS_SERVE_STATIC_FILES=true
    command: ["sh", "-c", "sudo cron && ./bin/rails db:create db:migrate && ./bin/rails server -b 0.0.0.0 -p 80"]