default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  
development:
  <<: *default
  database: db/development.sqlite3

development:
  <<: *default
  database: db/development.sqlite3

development:
  <<: *default
  database: db/development.sqlite3
