default: &default
  adapter: postgresql
  encoding: unicode
  host: postgres
  username: dev
  password: <%= ENV["DB_PASSWORD"] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: rss_dev


test:
  <<: *default
  database: rss_test

production:
  primary: &primary_production
    <<: *default
    database: rss_prod
    username: dev
    password: <%= ENV["DB_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: rss_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: rss_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: rss_production_cable
    migrations_paths: db/cable_migrate
