# Auto-generated seed file for rss_dev
Feed.delete_all

Feed.create!(id: 1, name: "Slashdot", url: "https://rss.slashdot.org/Slashdot/slashdot")
Feed.create!(id: 6, name: "Anime News Network", url: "https://www.animenewsnetwork.com/newsfeed/rss.xml")
Feed.create!(id: 8, name: "TechCrunch", url: "https://techcrunch.com/feed/")
Feed.create!(id: 9, name: "The Verge", url: "https://www.theverge.com/rss/full.xml")
Feed.create!(id: 10, name: "Wired", url: "https://www.wired.com/feed")
Feed.create!(id: 11, name: "MyAnimeList", url: "https://myanimelist.net/rss/news.xml")
Feed.create!(id: 13, name: "ArsTechnica", url: "https://arstechnica.com/information-technology/feed/")
Feed.create!(id: 15, name: "servethehome", url: "https://www.servethehome.com/feed/")
Feed.create!(id: 17, name: "Toms Hardware", url: "https://www.tomshardware.com/feeds.xml")
Feed.create!(id: 19, name: "Science Daily", url: "https://www.sciencedaily.com/rss/top/technology.xml")
Feed.create!(id: 20, name: "Play Asia", url: "https://play.asia/blog/feed/")
Feed.create!(id: 21, name: "IGN", url: "https://www.ign.com/rss/v2/articles/feed")
Feed.create!(id: 22, name: "changelog", url: "https://changelog.com/feed")
Feed.create!(id: 23, name: "gematsu", url: "https://www.gematsu.com/feed")
Feed.create!(id: 24, name: "sysadmin", url: "https://www.reddit.com/r/sysadmin.rss")
Feed.create!(id: 25, name: "programminghumor", url: "https://www.reddit.com/r/programminghumor.rss")
Feed.create!(id: 27, name: "AnimeCollectors", url: "https://www.reddit.com/r/AnimeCollectors.rss")
Feed.create!(id: 28, name: "anime", url: "https://www.reddit.com/r/anime.rss")
Feed.create!(id: 29, name: "Yattatachi", url: "https://yattatachi.com/feed")
Feed.create!(id: 34, name: "NVIDIA Newsroom", url: "https://nvidianews.nvidia.com/rss.xml")
Feed.create!(id: 48, name: "Skidrow-Games", url: "https://feeds.feedburner.com/skidrowgamesfeed")
Feed.create!(id: 55, name: "Limit Break Radio", url: "http://www.limitbreakradio.com/rss.xml")
Feed.create!(id: 65, name: "hackster.io", url: "https://www.hackster.io/projects?format=atom&sort=recent")
Feed.create!(id: 66, name: "Limited Run Games", url: "https://limitedrungames.com/blogs/news.atom")
Feed.create!(id: 68, name: "Anime Corner Store", url: "https://animecornerstore.blogspot.com/feeds/posts/default?alt=rss")
Feed.create!(id: 69, name: "[GM]Dave", url: "https://bannable-offenses.blogspot.com/feeds/posts/default")
Feed.create!(id: 80, name: "Microsoft Office Info", url: "https://status.cloud.microsoft/api/feed/mac")
Feed.create!(id: 145, name: "RSS", url: "http://192.168.1.150:31500/rss")
Feed.create!(id: 148, name: "Change Detection", url: "https://change.thestoryisover.net/rss?token=d6ae0e7ea3c04e95f0cc5df8f5a8d31e")
Feed.create!(id: 149, name: "Legal Mindset", url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCtiec4EBNN3iiNgXHgykm9A")
Feed.create!(id: 150, name: "DPatriot", url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCJPUolPbvMvGWLGhDJcnjJA")
Feed.create!(id: 153, name: "Dave's Garage", url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCNzszbnvQeFzObW0ghk0Ckw")
Feed.create!(id: 154, name: "Holo Subs EN", url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCMfgZuwBxJRhoahep4kRC5w")
Feed.create!(id: 155, name: "kumanuki", url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCYYlQ_kMJ5fV3RxpDd1TALQ")
Feed.create!(id: 156, name: "Matthew Shezmen", url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCB4WnO_ELLYdSBxiFn3Wn1A")
Feed.create!(id: 157, name: "Corridor Crew", url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCSpFnDQr88xCZ80N-X7t0nQ")
Feed.create!(id: 158, name: "Euro Brady", url: "https://www.youtube.com/feeds/videos.xml?channel_id=UC4ChspfTaiJcoHEs5b8_3IQ")
